version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: fciencias
      POSTGRES_PASSWORD: fciencias
      POSTGRES_DB: fciencias_dev
    ports: ["5432:5432"]
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fciencias"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fciencias.app
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: devaccess
      MINIO_ROOT_PASSWORD: devsecret
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata_dev:
  pgadmin_data:
  minio_data:
  redis_data:
